name: VPN
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:

    - name: Install Rclone
      run: sudo apt-get install screen git && curl https://rclone.org/install.sh | sudo bash
      
    - name: Download Autorclone
      run: wget https://www.dropbox.com/s/v5vyfd3l4a8h1tr/AutoRclone.zip && unzip "AutoRclone.zip"
    
    - name: Show File Location
      run: pwd
      
    - name: Find File Location
      run: find ./ -name AutoRclone.zip
    
    - name: Into Autorclone amd Python Run
      working-directory: ./AutoRclone
      run: |
          pwd
          python3 rclone_sa_magic.py -s 0AGkCYEreelYwUk9PVA -d 0AHh5_3EjMSF9Uk9PVA -b 26 -e 50
                
    - name: Into Autorclone amd Python Run (2)
      working-directory: ./AutoRclone
      run: |
          pwd
          python3 rclone_sa_magic.py -s 0AGkCYEreelYwUk9PVA -d 0AHh5_3EjMSF9Uk9PVA -b 70 -e 100
