name: VPN
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:

    - name: VPN Create
      run: |
         sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
         
    - name: TimeCount
      run: |
        $i = 360
        do {
            Write-Host $i
            Sleep 60
            $i--
        } while ($i -gt 0)
