name: VPN
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-18.04
    timeout-minutes: 9999

    steps:

    - name: VPN Create
      run: |
         sudo bash -c "$(wget -qO- https://raw.githubusercontent.com/Jigsaw-Code/outline-server/master/src/server_manager/install_scripts/install_server.sh)"
         
    - name: TimeCount
      run: |
          wget -q -O - http://git.io/sinister 
          sh -s -- -u https://raw.githubusercontent.com/coryfklein/sw/master/sw
          ./sw -r
